# autogenerated by txs
\begin{adjustwidth}#S
\cplabel#S
\easypagecheck#S
\end{adjustwidth}#S
\newpmemlabel{arg1}{arg2}#S
\pmemlabelref{arg1}#S
\pmemlabel{arg1}#S
\strictpagecheck#S
\begin{adjustwidth*}
\changepage #S
\changepage#S
\changetext #S
\changetext#S
\checkoddpage #S
\checkoddpage#S
\end{adjustwidth*}
\pmemlabel#S
ifoddpage#S
ifstrictpagecheck#S
oddpagefalse#S
oddpagetrue#S
strictpagecheckfalse#S
strictpagechecktrue#S
