# autogenerated by txs
\collectbox#S
\collectboxarray{arg1}{arg2}#S
\collectboxcheckenv{arg1}#S
\collectboxenvend#S
\collectboxtabularstar{arg1}{arg2}{arg3}{arg4}#S
\collectboxtabular{arg1}{arg2}{arg3}#S
\collectboxto#S
\collectboxto{arg1}#S
\ialign#S
\nocollectbox#S
\\collectboxtabular#S
\\collectboxtabularstar#S
\collectboxtabular#S
\collectedbox#S
collectboxenvfalse#S
collectboxenvtrue#S
ifcollectboxenv#S
