# autogenerated by txs
#include:color
#include:graphics
\CROP#S
\cropdef{arg1}{arg2}{arg3}{arg4}{arg5}{arg6}#S
\crop{arg1}#S
\expandafter#S
\x#S
\\crop#S
\\cropdef#S
\crop#S
\stockheight#S
\stockwidth#S
