# autogenerated by txs
#include:graphicx
\Gfigname#S
\epsfbox#S
\epsfclipoff#S
\epsfclipon#S
\epsfsize{arg1}#S
\epsfverbosefalse#S
\epsfverbosetrue#S
\psdraft#S
\psfigdriver{arg1}#S
\psfig{arg1}#S
\psfull#S
\psnoisy#S
\pssilent#S
\epsffile#S
\epsfig#S
\psfig#S
