# autogenerated by txs
#include:fp-basic
\FParccos{arg1}#S
\FParccot{arg1}#S
\FParcsincos{arg1}#S
\FParcsin{arg1}#S
\FParctancot{arg1}#S
\FParctan{arg1}#S
\FPcos{arg1}#S
\FPcot{arg1}#S
\FPsincos{arg1}#S
\FPsin{arg1}#S
\FPtancot{arg1}#S
\FPtan{arg1}#S
