# autogenerated by txs
#include:trig
\DeclareGraphicsExtensions{arg1}#S
\DeclareGraphicsRule{arg1}#S
\Gin#S
\Grot#S
\Gscale#S
\expandafter#S
\graphicspath{arg1}#S
\includegraphics#S
\noexpand#S
\reflectbox#S
\resizebox#S
\rotatebox{arg1}#S
\scalebox{arg1}#S
\MessageBreak#S
\protect#S
\toks0#S
