# autogenerated by txs
\marginfont#S
\marginnote#S
\marginnoteleftadjust#S
\marginnoterightadjust#S
\marginnotetextwidth#S
\marginnotevadjust#S
\newmarginnote#S
\raggedleftmarginnote#S
\raggedrightmarginnote#S
