# autogenerated by txs
#include:\@MDfont
#include:ifthen
#include:keyval
\ProcessUnusedOptions{arg1}#S
\WarningIfLoadedNoOption{arg1}#S
\WarningIfLoaded{arg1}#S
\ficshape{arg1}#S
\fscshape{arg1}#S
\?\figurecircled#S
\MDB-cmd#S
\MDB\figurecircled#S
\WarningIfLoaded#S
\figurecircled#S
