# autogenerated by txs
\mtcPackageError{arg1}{arg2}{arg3}{arg4}#S
\mtcPackageInfo{arg1}{arg2}{arg3}#S
\mtcPackageWarningNoLine{arg1}{arg2}{arg3}#S
\mtcPackageWarning{arg1}{arg2}{arg3}#S
\\mtcPackageError#S
\\mtcPackageInfo#S
\\mtcPackageWarning#S
\\mtcPackageWarningNoLine#S
\mtcPackageWarning#S
