# autogenerated by txs
\argdef#S
\bibliography{arg1}#S
\mylopoff{arg1}#S
\mylop{arg1}#S
\newcites{arg1}#S
\setbiblabelwidth{arg1}#S
\thebibliography{arg1}#S
\mylop#S
\newusecounter#S
\plugh#S
continuouslabelsfalse#S
continuouslabelstrue#S
ifcontinuouslabels#S
iflabeled#S
labeledfalse#S
labeledtrue#S
