# autogenerated by txs
#include:keyval
\DeclareFloatingEnvironment#S
\ForEachFloatingEnvironment#S
\PrepareListOf{arg1}#S
\SetupFloatingEnvironment{arg1}#S
\addtocontents{arg1}#S
\ext#S
\listoftoc#S
\newfloat#S
\newfloatsetup#S
\noexpand#S
\next#S
