# autogenerated by txs
#include:fontaxes
#include:xkeyval
\filedate#S
\fileversion#S
\L#S
\OT1\textcent#S
\\OT1\r-a#S
\l#S
\mathcent#S
\mathsterling#S
\sustyle #S
\sustyle#S
\textcent#S
\textdollar#S
\textsterling#S
