# autogenerated by txs
#include:ltxcmds
#include:pdftexcmds
\EdefEscapeHex{arg1}#S
\EdefEscapeName{arg1}#S
\EdefEscapeString{arg1}#S
\EdefSanitize{arg1}#S
\EdefUnescapeHex{arg1}#S
\EdefUnescapeName{arg1}#S
\EdefUnescapeString{arg1}#S
\empty#S
\expandafter#S
\expandafter{arg1}#S
\noexpand#S
\x#S
\x{arg1}#S
