# autogenerated by txs
\RaggedC#S
\RaggedL#S
\RaggedR#S
\TESTTEXT#S
\gobble{arg1}#S
\par#S
\raggedC#S
\raggedFrac{arg1}#S
\raggedHrule#S
\raggedL#S
\raggedR#S
\wlog{arg1}#S
\L23965#S
\Temp#S
\ragged.sty#S
\temp#S
