# autogenerated by txs
#include:atveryend
#include:infwarerr
#include:kvoptions
#include:pdftexcmds
#include:uniquecounter
\RerunFileCheck#S
\RerunFileCheckSetup#S
\RerunFileCheck{arg1}{arg2}{arg3}#S
\glossary#S
\index#S
\makeindex#S
\x#S
