# autogenerated by txs
#include:scrbase
#include:scrlfile
\AfterKOMAoptions#S
\KOMAExecuteOptions#S
\KOMAProcessOptions#S
\KOMAoptions{arg1}#S
\KOMAoption{arg1}{arg2}#S
\addtokomafont{arg1}{arg2}#S
\aliaskomafont{arg1}{arg2}#S
\csname#S
\expandafter#S
\newkomafont{arg1}{arg2}{arg3}#S
\scrlfileversion#S
\setkomafont{arg1}{arg2}#S
\usekomafont{arg1}#S
