# autogenerated by txs
#include:ifthen
\SC#S
\begin{SCfigure}#S
\begin{SCtable}#S
\begin{wide}#S
\end{SCfigure}#S
\end{SCtable}#S
\end{wide}#S
\sidecaptionrelwidth#S
\sidecaptionsep#S
\sidecaptionvpos{arg1}{arg2}#S
\begin{SCfigure*}
\begin{SCtable*}
\end{SCfigure*}
\end{SCtable*}
