# autogenerated by txs
\DoXPackageS#S
\docdate#S
\filedate#S
\fileinfo#S
\fileversion#S
\itswitch#S
\slswitch#S
\textitswitch#S
\textslswitch#S
\JusTLoaDInformatioN#S
\PPOptArg#S
\itswitch #S
\slswitch #S
\textitswitch #S
\textslswitch #S
