# autogenerated by txs
#include:caption
\p#S
\phantomsubcaption#S
\subcaption#S
\subcaptionbox#S
\subfigureautorefname#S
\subfigurename#S
\subref#S
\subtableautorefname#S
\subtablename#S
\theHsubfigure#S
\theHsubtable#S
\thesubfigure#S
\thesubtable#S
\toks0#S
