# autogenerated by txs
#include:scrkbase
\AfterCalculatingTypearea#S
\AfterSettingArea#S
\FamilyElseValue#S
\activateareas#S
\areaset{arg1}{arg2}{arg3}#S
\isopaper{arg1}{arg2}#S
\noexpand#S
\recalctypearea#S
\storeareas{arg1}#S
\ta#S
\typearea{arg1}{arg2}#S
