# autogenerated by txs
#include:expl3
\IfValueF#S
\IfValueT#S
\IfValueTF#S
\__xparse_add_arg:V#S
\__xparse_add_arg:o#S
\__xparse_add_arg_aux:V#S
\__xparse_add_expandable_type_+:w#S
\__xparse_add_expandable_type_>:w#S
\__xparse_add_type_+:w#S
\__xparse_add_type_>:w#S
\__xparse_count_type_+:w#S
\__xparse_count_type_>:w#S
\__xparse_declare_cmd_internal:cnx#S
\__xparse_grab_m_1:w#S
\__xparse_grab_m_2:w#S
\__xparse_grab_m_3:w#S
\__xparse_grab_m_4:w#S
\__xparse_grab_m_5:w#S
\__xparse_grab_m_6:w#S
\__xparse_grab_m_7:w#S
\__xparse_grab_m_8:w#S
\__xparse_if_no_value:nF#S
\__xparse_if_no_value:nT#S
\__xparse_if_no_value:nTF#S
\__xparse_put_arg_expandable:ow#S
\__xparse_split_list_multi:nV#S
\__xparse_split_list_multi:nn#S
\msg extra text > LaTeX/xparse/bad-arg-spec#S
\msg extra text > LaTeX/xparse/command-already-defined#S
\msg extra text > LaTeX/xparse/command-not-yet-defined#S
\msg extra text > LaTeX/xparse/define-command#S
\msg extra text > LaTeX/xparse/define-environment#S
\msg extra text > LaTeX/xparse/environment-already-defined#S
\msg extra text > LaTeX/xparse/environment-mismatch#S
\msg extra text > LaTeX/xparse/environment-not-yet-defined#S
\msg extra text > LaTeX/xparse/environment-unknown#S
\msg extra text > LaTeX/xparse/expandable-ending-optional#S
\msg extra text > LaTeX/xparse/inconsistent-long#S
\msg extra text > LaTeX/xparse/missing-required#S
\msg extra text > LaTeX/xparse/not-single-token#S
\msg extra text > LaTeX/xparse/processor-in-expandable#S
\msg extra text > LaTeX/xparse/redefine-command#S
\msg extra text > LaTeX/xparse/redefine-environment#S
\msg extra text > LaTeX/xparse/split-excess-tokens#S
\msg extra text > LaTeX/xparse/unknown-argument-type#S
\msg extra text > LaTeX/xparse/unknown-document-command#S
\msg extra text > LaTeX/xparse/verbatim-already-tokenized#S
\msg extra text > LaTeX/xparse/verbatim-newline#S
\msg text > LaTeX/xparse/bad-arg-spec#S
\msg text > LaTeX/xparse/command-already-defined#S
\msg text > LaTeX/xparse/command-not-yet-defined#S
\msg text > LaTeX/xparse/define-command#S
\msg text > LaTeX/xparse/define-environment#S
\msg text > LaTeX/xparse/environment-already-defined#S
\msg text > LaTeX/xparse/environment-mismatch#S
\msg text > LaTeX/xparse/environment-not-yet-defined#S
\msg text > LaTeX/xparse/environment-unknown#S
\msg text > LaTeX/xparse/expandable-ending-optional#S
\msg text > LaTeX/xparse/inconsistent-long#S
\msg text > LaTeX/xparse/invalid-expandable-argument-type#S
\msg text > LaTeX/xparse/missing-required#S
\msg text > LaTeX/xparse/not-single-token#S
\msg text > LaTeX/xparse/processor-in-expandable#S
\msg text > LaTeX/xparse/redefine-command#S
\msg text > LaTeX/xparse/redefine-environment#S
\msg text > LaTeX/xparse/split-excess-tokens#S
\msg text > LaTeX/xparse/unknown-argument-type#S
\msg text > LaTeX/xparse/unknown-document-command#S
\msg text > LaTeX/xparse/unknown-document-environment#S
\msg text > LaTeX/xparse/verbatim-already-tokenized#S
\msg text > LaTeX/xparse/verbatim-newline#S
\tempa#S
\tempb#S
